import type { MediaAsset } from '../../contracts/media.contract'
import { getDb } from '../../db/client'
import type { MediaStore } from '../../media/store'
import { createFolder } from './folder.service'
import * as repo from './media.repo'
import { uploadAsset } from './media.service'

/**
 * Files a module generates on the server — an issued invoice's PDF — entering
 * the shared library.
 *
 * Added for Invoices (`docs/v2/invoices.md`: "the finalized invoice PDF saved
 * privately in shared Media, organized in a folder such as `Invoices/2026`").
 * Nothing here is a new kind of storage: the bytes go through the ordinary
 * `uploadAsset`, so the type check, the pending-object ledger and the
 * duplicate-name rule are exactly those of a file uploaded by hand. What the
 * consuming module adds afterwards is a `record` reference — which is what
 * stops the file being deleted like an ordinary unused asset.
 */

const bytesStream = (bytes: Uint8Array): ReadableStream<Uint8Array> =>
  new ReadableStream<Uint8Array>({
    start(controller) {
      controller.enqueue(bytes)
      controller.close()
    },
  })

const findChildFolder = async (parentId: string | null, name: string): Promise<string | null> => {
  const { rows } = await getDb().query<{ id: string }>(
    `SELECT id FROM v2_media_folders
      WHERE lower(name) = lower($1) AND parent_id IS NOT DISTINCT FROM $2
      ORDER BY created_at, id LIMIT 1`,
    [name, parentId],
  )

  return rows[0]?.id ?? null
}

/** A child folder by name, created when missing — twice at once finds one. */
const ensureChild = async (parentId: string | null, name: string): Promise<string> => {
  const existing = await findChildFolder(parentId, name)

  if (existing) return existing

  try {
    return (await createFolder({ name, parentId })).id
  } catch (error) {
    const again = await findChildFolder(parentId, name)

    if (again) return again

    throw error
  }
}

/**
 * The module's folder, then a child inside it (a year).
 *
 * `rememberedRootId` is the folder the module used last time. While it still
 * exists it is used whatever the owner has renamed it to or wherever they
 * moved it, so organising the library never splits a module's files in two.
 * Only when it is gone is a folder called `rootName` found or created at the
 * library root.
 */
export const ensureModuleFolder = async (input: {
  rememberedRootId: string | null
  rootName: string
  childName: string
}): Promise<{ rootId: string; folderId: string }> => {
  const remembered = input.rememberedRootId ? await repo.findFolder(input.rememberedRootId) : null
  const rootId = remembered ? remembered.id : await ensureChild(null, input.rootName)
  const folderId = await ensureChild(rootId, input.childName)

  return { rootId, folderId }
}

/** Stores generated bytes as an ordinary library file in `folderId`. */
export const storeGeneratedFile = async (input: {
  bytes: Uint8Array
  fileName: string
  folderId: string | null
  store?: MediaStore
}): Promise<MediaAsset> => {
  const { asset } = await uploadAsset({
    body: bytesStream(input.bytes),
    declaredSize: input.bytes.byteLength,
    fileName: input.fileName,
    folderId: input.folderId,
    store: input.store,
  })

  return asset
}
