/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as LangRouteImport } from './../routes/$lang'
import { Route as AdminRouteImport } from './../routes/admin'
import { Route as SitemapDotxmlRouteImport } from './../routes/sitemap[.]xml'
import { Route as LangIndexRouteImport } from './../routes/$lang.index'
import { Route as LangAboutRouteImport } from './../routes/$lang.about'
import { Route as LangContactRouteImport } from './../routes/$lang.contact'
import { Route as LangDatenschutzRouteImport } from './../routes/$lang.datenschutz'
import { Route as LangFaqRouteImport } from './../routes/$lang.faq'
import { Route as LangImpressumRouteImport } from './../routes/$lang.impressum'
import { Route as LangServicesRouteImport } from './../routes/$lang.services'
import { Route as LangStackRouteImport } from './../routes/$lang.stack'
import { Route as AdminIndexRouteImport } from './../routes/admin.index'
import { Route as AdminLoginRouteImport } from './../routes/admin_.login'
import { Route as ApiSplatRouteImport } from './../routes/api.$'
import { Route as ApiContactRouteImport } from './../routes/api/contact'
import { Route as LangWorkIndexRouteImport } from './../routes/$lang.work.index'
import { Route as LangWorkSlugRouteImport } from './../routes/$lang.work.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LangAboutRoute = LangAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LangRoute,
} as any)
const LangContactRoute = LangContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LangRoute,
} as any)
const LangDatenschutzRoute = LangDatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => LangRoute,
} as any)
const LangFaqRoute = LangFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => LangRoute,
} as any)
const LangImpressumRoute = LangImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => LangRoute,
} as any)
const LangServicesRoute = LangServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => LangRoute,
} as any)
const LangStackRoute = LangStackRouteImport.update({
  id: '/stack',
  path: '/stack',
  getParentRoute: () => LangRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LangWorkIndexRoute = LangWorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => LangRoute,
} as any)
const LangWorkSlugRoute = LangWorkSlugRouteImport.update({
  id: '/work/$slug',
  path: '/work/$slug',
  getParentRoute: () => LangRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/datenschutz': typeof LangDatenschutzRoute
  '/$lang/faq': typeof LangFaqRoute
  '/$lang/impressum': typeof LangImpressumRoute
  '/$lang/services': typeof LangServicesRoute
  '/$lang/stack': typeof LangStackRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/$': typeof ApiSplatRoute
  '/api/contact': typeof ApiContactRoute
  '/$lang/': typeof LangIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/$lang/work/$slug': typeof LangWorkSlugRoute
  '/$lang/work/': typeof LangWorkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/datenschutz': typeof LangDatenschutzRoute
  '/$lang/faq': typeof LangFaqRoute
  '/$lang/impressum': typeof LangImpressumRoute
  '/$lang/services': typeof LangServicesRoute
  '/$lang/stack': typeof LangStackRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/$': typeof ApiSplatRoute
  '/api/contact': typeof ApiContactRoute
  '/$lang': typeof LangIndexRoute
  '/admin': typeof AdminIndexRoute
  '/$lang/work/$slug': typeof LangWorkSlugRoute
  '/$lang/work': typeof LangWorkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/datenschutz': typeof LangDatenschutzRoute
  '/$lang/faq': typeof LangFaqRoute
  '/$lang/impressum': typeof LangImpressumRoute
  '/$lang/services': typeof LangServicesRoute
  '/$lang/stack': typeof LangStackRoute
  '/admin_/login': typeof AdminLoginRoute
  '/api/$': typeof ApiSplatRoute
  '/api/contact': typeof ApiContactRoute
  '/$lang/': typeof LangIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/$lang/work/$slug': typeof LangWorkSlugRoute
  '/$lang/work/': typeof LangWorkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/admin'
    | '/sitemap.xml'
    | '/$lang/about'
    | '/$lang/contact'
    | '/$lang/datenschutz'
    | '/$lang/faq'
    | '/$lang/impressum'
    | '/$lang/services'
    | '/$lang/stack'
    | '/admin/login'
    | '/api/$'
    | '/api/contact'
    | '/$lang/'
    | '/admin/'
    | '/$lang/work/$slug'
    | '/$lang/work/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/$lang/about'
    | '/$lang/contact'
    | '/$lang/datenschutz'
    | '/$lang/faq'
    | '/$lang/impressum'
    | '/$lang/services'
    | '/$lang/stack'
    | '/admin/login'
    | '/api/$'
    | '/api/contact'
    | '/$lang'
    | '/admin'
    | '/$lang/work/$slug'
    | '/$lang/work'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/admin'
    | '/sitemap.xml'
    | '/$lang/about'
    | '/$lang/contact'
    | '/$lang/datenschutz'
    | '/$lang/faq'
    | '/$lang/impressum'
    | '/$lang/services'
    | '/$lang/stack'
    | '/admin_/login'
    | '/api/$'
    | '/api/contact'
    | '/$lang/'
    | '/admin/'
    | '/$lang/work/$slug'
    | '/$lang/work/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiContactRoute: typeof ApiContactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/about': {
      id: '/$lang/about'
      path: '/about'
      fullPath: '/$lang/about'
      preLoaderRoute: typeof LangAboutRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/contact': {
      id: '/$lang/contact'
      path: '/contact'
      fullPath: '/$lang/contact'
      preLoaderRoute: typeof LangContactRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/datenschutz': {
      id: '/$lang/datenschutz'
      path: '/datenschutz'
      fullPath: '/$lang/datenschutz'
      preLoaderRoute: typeof LangDatenschutzRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/faq': {
      id: '/$lang/faq'
      path: '/faq'
      fullPath: '/$lang/faq'
      preLoaderRoute: typeof LangFaqRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/impressum': {
      id: '/$lang/impressum'
      path: '/impressum'
      fullPath: '/$lang/impressum'
      preLoaderRoute: typeof LangImpressumRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/services': {
      id: '/$lang/services'
      path: '/services'
      fullPath: '/$lang/services'
      preLoaderRoute: typeof LangServicesRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/stack': {
      id: '/$lang/stack'
      path: '/stack'
      fullPath: '/$lang/stack'
      preLoaderRoute: typeof LangStackRouteImport
      parentRoute: typeof LangRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/work/': {
      id: '/$lang/work/'
      path: '/work'
      fullPath: '/$lang/work/'
      preLoaderRoute: typeof LangWorkIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/work/$slug': {
      id: '/$lang/work/$slug'
      path: '/work/$slug'
      fullPath: '/$lang/work/$slug'
      preLoaderRoute: typeof LangWorkSlugRouteImport
      parentRoute: typeof LangRoute
    }
  }
}

interface LangRouteChildren {
  LangAboutRoute: typeof LangAboutRoute
  LangContactRoute: typeof LangContactRoute
  LangDatenschutzRoute: typeof LangDatenschutzRoute
  LangFaqRoute: typeof LangFaqRoute
  LangImpressumRoute: typeof LangImpressumRoute
  LangServicesRoute: typeof LangServicesRoute
  LangStackRoute: typeof LangStackRoute
  LangIndexRoute: typeof LangIndexRoute
  LangWorkSlugRoute: typeof LangWorkSlugRoute
  LangWorkIndexRoute: typeof LangWorkIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangAboutRoute: LangAboutRoute,
  LangContactRoute: LangContactRoute,
  LangDatenschutzRoute: LangDatenschutzRoute,
  LangFaqRoute: LangFaqRoute,
  LangImpressumRoute: LangImpressumRoute,
  LangServicesRoute: LangServicesRoute,
  LangStackRoute: LangStackRoute,
  LangIndexRoute: LangIndexRoute,
  LangWorkSlugRoute: LangWorkSlugRoute,
  LangWorkIndexRoute: LangWorkIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminLoginRoute: AdminLoginRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiContactRoute: ApiContactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
