/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as LangRouteImport } from './../routes/$lang'
import { Route as AdminRouteImport } from './../routes/admin'
import { Route as SitemapDotxmlRouteImport } from './../routes/sitemap[.]xml'
import { Route as LangIndexRouteImport } from './../routes/$lang.index'
import { Route as LangAboutRouteImport } from './../routes/$lang.about'
import { Route as LangContactRouteImport } from './../routes/$lang.contact'
import { Route as LangDatenschutzRouteImport } from './../routes/$lang.datenschutz'
import { Route as LangFaqRouteImport } from './../routes/$lang.faq'
import { Route as LangImpressumRouteImport } from './../routes/$lang.impressum'
import { Route as LangServicesRouteImport } from './../routes/$lang.services'
import { Route as LangStackRouteImport } from './../routes/$lang.stack'
import { Route as AdminIndexRouteImport } from './../routes/admin.index'
import { Route as AdminContentRouteImport } from './../routes/admin.content'
import { Route as AdminLoginRouteImport } from './../routes/admin_.login'
import { Route as ApiSplatRouteImport } from './../routes/api.$'
import { Route as ApiContactRouteImport } from './../routes/api/contact'
import { Route as ApiInboundEmailRouteImport } from './../routes/api/inbound-email'
import { Route as RssArDotxmlRouteImport } from './../routes/rss.ar[.]xml'
import { Route as RssDeDotxmlRouteImport } from './../routes/rss.de[.]xml'
import { Route as RssEnDotxmlRouteImport } from './../routes/rss.en[.]xml'
import { Route as LangBlogIndexRouteImport } from './../routes/$lang.blog.index'
import { Route as LangBlogSlugRouteImport } from './../routes/$lang.blog.$slug'
import { Route as LangBookingIndexRouteImport } from './../routes/$lang.booking.index'
import { Route as LangBookingSlugRouteImport } from './../routes/$lang.booking.$slug'
import { Route as LangWorkIndexRouteImport } from './../routes/$lang.work.index'
import { Route as LangWorkSlugRouteImport } from './../routes/$lang.work.$slug'
import { Route as AdminBlogIndexRouteImport } from './../routes/admin.blog.index'
import { Route as AdminBlogIdRouteImport } from './../routes/admin.blog.$id'
import { Route as AdminBlogNewRouteImport } from './../routes/admin.blog.new'
import { Route as AdminBlogTagsRouteImport } from './../routes/admin.blog.tags'
import { Route as AdminBookingsIndexRouteImport } from './../routes/admin.bookings.index'
import { Route as AdminBookingsIdRouteImport } from './../routes/admin.bookings.$id'
import { Route as AdminBookingsAvailabilityRouteImport } from './../routes/admin.bookings.availability'
import { Route as AdminBookingsNewRouteImport } from './../routes/admin.bookings.new'
import { Route as AdminInboxIndexRouteImport } from './../routes/admin.inbox.index'
import { Route as AdminInboxPersonIdRouteImport } from './../routes/admin.inbox.$personId'
import { Route as AdminInboxNewRouteImport } from './../routes/admin.inbox.new'
import { Route as AdminInboxSettingsRouteImport } from './../routes/admin.inbox.settings'
import { Route as AdminInvoicesIndexRouteImport } from './../routes/admin.invoices.index'
import { Route as AdminInvoicesInvoiceIdRouteImport } from './../routes/admin.invoices.$invoiceId'
import { Route as AdminInvoicesClientsRouteImport } from './../routes/admin.invoices.clients'
import { Route as AdminInvoicesNewRouteImport } from './../routes/admin.invoices.new'
import { Route as AdminInvoicesSentRouteImport } from './../routes/admin.invoices.sent'
import { Route as AdminInvoicesSubscriptionsRouteImport } from './../routes/admin.invoices.subscriptions'
import { Route as AdminLeadsIndexRouteImport } from './../routes/admin.leads.index'
import { Route as AdminLeadsPersonIdRouteImport } from './../routes/admin.leads.$personId'
import { Route as AdminLeadsBoardRouteImport } from './../routes/admin.leads.board'
import { Route as AdminProjectsIndexRouteImport } from './../routes/admin.projects.index'
import { Route as AdminProjectsIdRouteImport } from './../routes/admin.projects.$id'
import { Route as AdminProjectsNewRouteImport } from './../routes/admin.projects.new'
import { Route as LangBookingManageReferenceRouteImport } from './../routes/$lang.booking.manage.$reference'
import { Route as LangBookingRoomReferenceRouteImport } from './../routes/$lang.booking.room.$reference'
import { Route as AdminBookingsIdRoomRouteImport } from './../routes/admin.bookings.$id_.room'
import { Route as AdminBookingsTypesIndexRouteImport } from './../routes/admin.bookings.types.index'
import { Route as AdminBookingsTypesIdRouteImport } from './../routes/admin.bookings.types.$id'
import { Route as AdminBookingsTypesNewRouteImport } from './../routes/admin.bookings.types.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LangAboutRoute = LangAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LangRoute,
} as any)
const LangContactRoute = LangContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LangRoute,
} as any)
const LangDatenschutzRoute = LangDatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => LangRoute,
} as any)
const LangFaqRoute = LangFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => LangRoute,
} as any)
const LangImpressumRoute = LangImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => LangRoute,
} as any)
const LangServicesRoute = LangServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => LangRoute,
} as any)
const LangStackRoute = LangStackRouteImport.update({
  id: '/stack',
  path: '/stack',
  getParentRoute: () => LangRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInboundEmailRoute = ApiInboundEmailRouteImport.update({
  id: '/api/inbound-email',
  path: '/api/inbound-email',
  getParentRoute: () => rootRouteImport,
} as any)
const RssArDotxmlRoute = RssArDotxmlRouteImport.update({
  id: '/rss/ar.xml',
  path: '/rss/ar.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDeDotxmlRoute = RssDeDotxmlRouteImport.update({
  id: '/rss/de.xml',
  path: '/rss/de.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RssEnDotxmlRoute = RssEnDotxmlRouteImport.update({
  id: '/rss/en.xml',
  path: '/rss/en.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LangBlogIndexRoute = LangBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => LangRoute,
} as any)
const LangBlogSlugRoute = LangBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => LangRoute,
} as any)
const LangBookingIndexRoute = LangBookingIndexRouteImport.update({
  id: '/booking/',
  path: '/booking/',
  getParentRoute: () => LangRoute,
} as any)
const LangBookingSlugRoute = LangBookingSlugRouteImport.update({
  id: '/booking/$slug',
  path: '/booking/$slug',
  getParentRoute: () => LangRoute,
} as any)
const LangWorkIndexRoute = LangWorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => LangRoute,
} as any)
const LangWorkSlugRoute = LangWorkSlugRouteImport.update({
  id: '/work/$slug',
  path: '/work/$slug',
  getParentRoute: () => LangRoute,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogIdRoute = AdminBlogIdRouteImport.update({
  id: '/blog/$id',
  path: '/blog/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogNewRoute = AdminBlogNewRouteImport.update({
  id: '/blog/new',
  path: '/blog/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogTagsRoute = AdminBlogTagsRouteImport.update({
  id: '/blog/tags',
  path: '/blog/tags',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsIndexRoute = AdminBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsIdRoute = AdminBookingsIdRouteImport.update({
  id: '/bookings/$id',
  path: '/bookings/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsAvailabilityRoute =
  AdminBookingsAvailabilityRouteImport.update({
    id: '/bookings/availability',
    path: '/bookings/availability',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminBookingsNewRoute = AdminBookingsNewRouteImport.update({
  id: '/bookings/new',
  path: '/bookings/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInboxIndexRoute = AdminInboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInboxPersonIdRoute = AdminInboxPersonIdRouteImport.update({
  id: '/inbox/$personId',
  path: '/inbox/$personId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInboxNewRoute = AdminInboxNewRouteImport.update({
  id: '/inbox/new',
  path: '/inbox/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInboxSettingsRoute = AdminInboxSettingsRouteImport.update({
  id: '/inbox/settings',
  path: '/inbox/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvoicesIndexRoute = AdminInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvoicesInvoiceIdRoute = AdminInvoicesInvoiceIdRouteImport.update({
  id: '/invoices/$invoiceId',
  path: '/invoices/$invoiceId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvoicesClientsRoute = AdminInvoicesClientsRouteImport.update({
  id: '/invoices/clients',
  path: '/invoices/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvoicesNewRoute = AdminInvoicesNewRouteImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvoicesSentRoute = AdminInvoicesSentRouteImport.update({
  id: '/invoices/sent',
  path: '/invoices/sent',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvoicesSubscriptionsRoute =
  AdminInvoicesSubscriptionsRouteImport.update({
    id: '/invoices/subscriptions',
    path: '/invoices/subscriptions',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminLeadsIndexRoute = AdminLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsPersonIdRoute = AdminLeadsPersonIdRouteImport.update({
  id: '/leads/$personId',
  path: '/leads/$personId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsBoardRoute = AdminLeadsBoardRouteImport.update({
  id: '/leads/board',
  path: '/leads/board',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsIndexRoute = AdminProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsIdRoute = AdminProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsNewRoute = AdminProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => AdminRoute,
} as any)
const LangBookingManageReferenceRoute =
  LangBookingManageReferenceRouteImport.update({
    id: '/booking/manage/$reference',
    path: '/booking/manage/$reference',
    getParentRoute: () => LangRoute,
  } as any)
const LangBookingRoomReferenceRoute =
  LangBookingRoomReferenceRouteImport.update({
    id: '/booking/room/$reference',
    path: '/booking/room/$reference',
    getParentRoute: () => LangRoute,
  } as any)
const AdminBookingsIdRoomRoute = AdminBookingsIdRoomRouteImport.update({
  id: '/bookings/$id_/room',
  path: '/bookings/$id/room',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsTypesIndexRoute = AdminBookingsTypesIndexRouteImport.update({
  id: '/bookings/types/',
  path: '/bookings/types/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsTypesIdRoute = AdminBookingsTypesIdRouteImport.update({
  id: '/bookings/types/$id',
  path: '/bookings/types/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsTypesNewRoute = AdminBookingsTypesNewRouteImport.update({
  id: '/bookings/types/new',
  path: '/bookings/types/new',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/datenschutz': typeof LangDatenschutzRoute
  '/$lang/faq': typeof LangFaqRoute
  '/$lang/impressum': typeof LangImpressumRoute
  '/$lang/services': typeof LangServicesRoute
  '/$lang/stack': typeof LangStackRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/$': typeof ApiSplatRoute
  '/api/contact': typeof ApiContactRoute
  '/api/inbound-email': typeof ApiInboundEmailRoute
  '/rss/ar.xml': typeof RssArDotxmlRoute
  '/rss/de.xml': typeof RssDeDotxmlRoute
  '/rss/en.xml': typeof RssEnDotxmlRoute
  '/$lang/': typeof LangIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/$lang/blog/$slug': typeof LangBlogSlugRoute
  '/$lang/booking/$slug': typeof LangBookingSlugRoute
  '/$lang/work/$slug': typeof LangWorkSlugRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/blog/tags': typeof AdminBlogTagsRoute
  '/admin/bookings/$id': typeof AdminBookingsIdRoute
  '/admin/bookings/availability': typeof AdminBookingsAvailabilityRoute
  '/admin/bookings/new': typeof AdminBookingsNewRoute
  '/admin/inbox/$personId': typeof AdminInboxPersonIdRoute
  '/admin/inbox/new': typeof AdminInboxNewRoute
  '/admin/inbox/settings': typeof AdminInboxSettingsRoute
  '/admin/invoices/$invoiceId': typeof AdminInvoicesInvoiceIdRoute
  '/admin/invoices/clients': typeof AdminInvoicesClientsRoute
  '/admin/invoices/new': typeof AdminInvoicesNewRoute
  '/admin/invoices/sent': typeof AdminInvoicesSentRoute
  '/admin/invoices/subscriptions': typeof AdminInvoicesSubscriptionsRoute
  '/admin/leads/$personId': typeof AdminLeadsPersonIdRoute
  '/admin/leads/board': typeof AdminLeadsBoardRoute
  '/admin/projects/$id': typeof AdminProjectsIdRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/$lang/blog/': typeof LangBlogIndexRoute
  '/$lang/booking/': typeof LangBookingIndexRoute
  '/$lang/work/': typeof LangWorkIndexRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/bookings/': typeof AdminBookingsIndexRoute
  '/admin/inbox/': typeof AdminInboxIndexRoute
  '/admin/invoices/': typeof AdminInvoicesIndexRoute
  '/admin/leads/': typeof AdminLeadsIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/$lang/booking/manage/$reference': typeof LangBookingManageReferenceRoute
  '/$lang/booking/room/$reference': typeof LangBookingRoomReferenceRoute
  '/admin/bookings/$id/room': typeof AdminBookingsIdRoomRoute
  '/admin/bookings/types/$id': typeof AdminBookingsTypesIdRoute
  '/admin/bookings/types/new': typeof AdminBookingsTypesNewRoute
  '/admin/bookings/types/': typeof AdminBookingsTypesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/datenschutz': typeof LangDatenschutzRoute
  '/$lang/faq': typeof LangFaqRoute
  '/$lang/impressum': typeof LangImpressumRoute
  '/$lang/services': typeof LangServicesRoute
  '/$lang/stack': typeof LangStackRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/$': typeof ApiSplatRoute
  '/api/contact': typeof ApiContactRoute
  '/api/inbound-email': typeof ApiInboundEmailRoute
  '/rss/ar.xml': typeof RssArDotxmlRoute
  '/rss/de.xml': typeof RssDeDotxmlRoute
  '/rss/en.xml': typeof RssEnDotxmlRoute
  '/$lang': typeof LangIndexRoute
  '/admin': typeof AdminIndexRoute
  '/$lang/blog/$slug': typeof LangBlogSlugRoute
  '/$lang/booking/$slug': typeof LangBookingSlugRoute
  '/$lang/work/$slug': typeof LangWorkSlugRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/blog/tags': typeof AdminBlogTagsRoute
  '/admin/bookings/$id': typeof AdminBookingsIdRoute
  '/admin/bookings/availability': typeof AdminBookingsAvailabilityRoute
  '/admin/bookings/new': typeof AdminBookingsNewRoute
  '/admin/inbox/$personId': typeof AdminInboxPersonIdRoute
  '/admin/inbox/new': typeof AdminInboxNewRoute
  '/admin/inbox/settings': typeof AdminInboxSettingsRoute
  '/admin/invoices/$invoiceId': typeof AdminInvoicesInvoiceIdRoute
  '/admin/invoices/clients': typeof AdminInvoicesClientsRoute
  '/admin/invoices/new': typeof AdminInvoicesNewRoute
  '/admin/invoices/sent': typeof AdminInvoicesSentRoute
  '/admin/invoices/subscriptions': typeof AdminInvoicesSubscriptionsRoute
  '/admin/leads/$personId': typeof AdminLeadsPersonIdRoute
  '/admin/leads/board': typeof AdminLeadsBoardRoute
  '/admin/projects/$id': typeof AdminProjectsIdRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/$lang/blog': typeof LangBlogIndexRoute
  '/$lang/booking': typeof LangBookingIndexRoute
  '/$lang/work': typeof LangWorkIndexRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/bookings': typeof AdminBookingsIndexRoute
  '/admin/inbox': typeof AdminInboxIndexRoute
  '/admin/invoices': typeof AdminInvoicesIndexRoute
  '/admin/leads': typeof AdminLeadsIndexRoute
  '/admin/projects': typeof AdminProjectsIndexRoute
  '/$lang/booking/manage/$reference': typeof LangBookingManageReferenceRoute
  '/$lang/booking/room/$reference': typeof LangBookingRoomReferenceRoute
  '/admin/bookings/$id/room': typeof AdminBookingsIdRoomRoute
  '/admin/bookings/types/$id': typeof AdminBookingsTypesIdRoute
  '/admin/bookings/types/new': typeof AdminBookingsTypesNewRoute
  '/admin/bookings/types': typeof AdminBookingsTypesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/datenschutz': typeof LangDatenschutzRoute
  '/$lang/faq': typeof LangFaqRoute
  '/$lang/impressum': typeof LangImpressumRoute
  '/$lang/services': typeof LangServicesRoute
  '/$lang/stack': typeof LangStackRoute
  '/admin/content': typeof AdminContentRoute
  '/admin_/login': typeof AdminLoginRoute
  '/api/$': typeof ApiSplatRoute
  '/api/contact': typeof ApiContactRoute
  '/api/inbound-email': typeof ApiInboundEmailRoute
  '/rss/ar.xml': typeof RssArDotxmlRoute
  '/rss/de.xml': typeof RssDeDotxmlRoute
  '/rss/en.xml': typeof RssEnDotxmlRoute
  '/$lang/': typeof LangIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/$lang/blog/$slug': typeof LangBlogSlugRoute
  '/$lang/booking/$slug': typeof LangBookingSlugRoute
  '/$lang/work/$slug': typeof LangWorkSlugRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/blog/tags': typeof AdminBlogTagsRoute
  '/admin/bookings/$id': typeof AdminBookingsIdRoute
  '/admin/bookings/availability': typeof AdminBookingsAvailabilityRoute
  '/admin/bookings/new': typeof AdminBookingsNewRoute
  '/admin/inbox/$personId': typeof AdminInboxPersonIdRoute
  '/admin/inbox/new': typeof AdminInboxNewRoute
  '/admin/inbox/settings': typeof AdminInboxSettingsRoute
  '/admin/invoices/$invoiceId': typeof AdminInvoicesInvoiceIdRoute
  '/admin/invoices/clients': typeof AdminInvoicesClientsRoute
  '/admin/invoices/new': typeof AdminInvoicesNewRoute
  '/admin/invoices/sent': typeof AdminInvoicesSentRoute
  '/admin/invoices/subscriptions': typeof AdminInvoicesSubscriptionsRoute
  '/admin/leads/$personId': typeof AdminLeadsPersonIdRoute
  '/admin/leads/board': typeof AdminLeadsBoardRoute
  '/admin/projects/$id': typeof AdminProjectsIdRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/$lang/blog/': typeof LangBlogIndexRoute
  '/$lang/booking/': typeof LangBookingIndexRoute
  '/$lang/work/': typeof LangWorkIndexRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/bookings/': typeof AdminBookingsIndexRoute
  '/admin/inbox/': typeof AdminInboxIndexRoute
  '/admin/invoices/': typeof AdminInvoicesIndexRoute
  '/admin/leads/': typeof AdminLeadsIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/$lang/booking/manage/$reference': typeof LangBookingManageReferenceRoute
  '/$lang/booking/room/$reference': typeof LangBookingRoomReferenceRoute
  '/admin/bookings/$id_/room': typeof AdminBookingsIdRoomRoute
  '/admin/bookings/types/$id': typeof AdminBookingsTypesIdRoute
  '/admin/bookings/types/new': typeof AdminBookingsTypesNewRoute
  '/admin/bookings/types/': typeof AdminBookingsTypesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/admin'
    | '/sitemap.xml'
    | '/$lang/about'
    | '/$lang/contact'
    | '/$lang/datenschutz'
    | '/$lang/faq'
    | '/$lang/impressum'
    | '/$lang/services'
    | '/$lang/stack'
    | '/admin/content'
    | '/admin/login'
    | '/api/$'
    | '/api/contact'
    | '/api/inbound-email'
    | '/rss/ar.xml'
    | '/rss/de.xml'
    | '/rss/en.xml'
    | '/$lang/'
    | '/admin/'
    | '/$lang/blog/$slug'
    | '/$lang/booking/$slug'
    | '/$lang/work/$slug'
    | '/admin/blog/$id'
    | '/admin/blog/new'
    | '/admin/blog/tags'
    | '/admin/bookings/$id'
    | '/admin/bookings/availability'
    | '/admin/bookings/new'
    | '/admin/inbox/$personId'
    | '/admin/inbox/new'
    | '/admin/inbox/settings'
    | '/admin/invoices/$invoiceId'
    | '/admin/invoices/clients'
    | '/admin/invoices/new'
    | '/admin/invoices/sent'
    | '/admin/invoices/subscriptions'
    | '/admin/leads/$personId'
    | '/admin/leads/board'
    | '/admin/projects/$id'
    | '/admin/projects/new'
    | '/$lang/blog/'
    | '/$lang/booking/'
    | '/$lang/work/'
    | '/admin/blog/'
    | '/admin/bookings/'
    | '/admin/inbox/'
    | '/admin/invoices/'
    | '/admin/leads/'
    | '/admin/projects/'
    | '/$lang/booking/manage/$reference'
    | '/$lang/booking/room/$reference'
    | '/admin/bookings/$id/room'
    | '/admin/bookings/types/$id'
    | '/admin/bookings/types/new'
    | '/admin/bookings/types/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/$lang/about'
    | '/$lang/contact'
    | '/$lang/datenschutz'
    | '/$lang/faq'
    | '/$lang/impressum'
    | '/$lang/services'
    | '/$lang/stack'
    | '/admin/content'
    | '/admin/login'
    | '/api/$'
    | '/api/contact'
    | '/api/inbound-email'
    | '/rss/ar.xml'
    | '/rss/de.xml'
    | '/rss/en.xml'
    | '/$lang'
    | '/admin'
    | '/$lang/blog/$slug'
    | '/$lang/booking/$slug'
    | '/$lang/work/$slug'
    | '/admin/blog/$id'
    | '/admin/blog/new'
    | '/admin/blog/tags'
    | '/admin/bookings/$id'
    | '/admin/bookings/availability'
    | '/admin/bookings/new'
    | '/admin/inbox/$personId'
    | '/admin/inbox/new'
    | '/admin/inbox/settings'
    | '/admin/invoices/$invoiceId'
    | '/admin/invoices/clients'
    | '/admin/invoices/new'
    | '/admin/invoices/sent'
    | '/admin/invoices/subscriptions'
    | '/admin/leads/$personId'
    | '/admin/leads/board'
    | '/admin/projects/$id'
    | '/admin/projects/new'
    | '/$lang/blog'
    | '/$lang/booking'
    | '/$lang/work'
    | '/admin/blog'
    | '/admin/bookings'
    | '/admin/inbox'
    | '/admin/invoices'
    | '/admin/leads'
    | '/admin/projects'
    | '/$lang/booking/manage/$reference'
    | '/$lang/booking/room/$reference'
    | '/admin/bookings/$id/room'
    | '/admin/bookings/types/$id'
    | '/admin/bookings/types/new'
    | '/admin/bookings/types'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/admin'
    | '/sitemap.xml'
    | '/$lang/about'
    | '/$lang/contact'
    | '/$lang/datenschutz'
    | '/$lang/faq'
    | '/$lang/impressum'
    | '/$lang/services'
    | '/$lang/stack'
    | '/admin/content'
    | '/admin_/login'
    | '/api/$'
    | '/api/contact'
    | '/api/inbound-email'
    | '/rss/ar.xml'
    | '/rss/de.xml'
    | '/rss/en.xml'
    | '/$lang/'
    | '/admin/'
    | '/$lang/blog/$slug'
    | '/$lang/booking/$slug'
    | '/$lang/work/$slug'
    | '/admin/blog/$id'
    | '/admin/blog/new'
    | '/admin/blog/tags'
    | '/admin/bookings/$id'
    | '/admin/bookings/availability'
    | '/admin/bookings/new'
    | '/admin/inbox/$personId'
    | '/admin/inbox/new'
    | '/admin/inbox/settings'
    | '/admin/invoices/$invoiceId'
    | '/admin/invoices/clients'
    | '/admin/invoices/new'
    | '/admin/invoices/sent'
    | '/admin/invoices/subscriptions'
    | '/admin/leads/$personId'
    | '/admin/leads/board'
    | '/admin/projects/$id'
    | '/admin/projects/new'
    | '/$lang/blog/'
    | '/$lang/booking/'
    | '/$lang/work/'
    | '/admin/blog/'
    | '/admin/bookings/'
    | '/admin/inbox/'
    | '/admin/invoices/'
    | '/admin/leads/'
    | '/admin/projects/'
    | '/$lang/booking/manage/$reference'
    | '/$lang/booking/room/$reference'
    | '/admin/bookings/$id_/room'
    | '/admin/bookings/types/$id'
    | '/admin/bookings/types/new'
    | '/admin/bookings/types/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiInboundEmailRoute: typeof ApiInboundEmailRoute
  RssArDotxmlRoute: typeof RssArDotxmlRoute
  RssDeDotxmlRoute: typeof RssDeDotxmlRoute
  RssEnDotxmlRoute: typeof RssEnDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/about': {
      id: '/$lang/about'
      path: '/about'
      fullPath: '/$lang/about'
      preLoaderRoute: typeof LangAboutRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/contact': {
      id: '/$lang/contact'
      path: '/contact'
      fullPath: '/$lang/contact'
      preLoaderRoute: typeof LangContactRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/datenschutz': {
      id: '/$lang/datenschutz'
      path: '/datenschutz'
      fullPath: '/$lang/datenschutz'
      preLoaderRoute: typeof LangDatenschutzRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/faq': {
      id: '/$lang/faq'
      path: '/faq'
      fullPath: '/$lang/faq'
      preLoaderRoute: typeof LangFaqRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/impressum': {
      id: '/$lang/impressum'
      path: '/impressum'
      fullPath: '/$lang/impressum'
      preLoaderRoute: typeof LangImpressumRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/services': {
      id: '/$lang/services'
      path: '/services'
      fullPath: '/$lang/services'
      preLoaderRoute: typeof LangServicesRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/stack': {
      id: '/$lang/stack'
      path: '/stack'
      fullPath: '/$lang/stack'
      preLoaderRoute: typeof LangStackRouteImport
      parentRoute: typeof LangRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inbound-email': {
      id: '/api/inbound-email'
      path: '/api/inbound-email'
      fullPath: '/api/inbound-email'
      preLoaderRoute: typeof ApiInboundEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss/ar.xml': {
      id: '/rss/ar.xml'
      path: '/rss/ar.xml'
      fullPath: '/rss/ar.xml'
      preLoaderRoute: typeof RssArDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss/de.xml': {
      id: '/rss/de.xml'
      path: '/rss/de.xml'
      fullPath: '/rss/de.xml'
      preLoaderRoute: typeof RssDeDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss/en.xml': {
      id: '/rss/en.xml'
      path: '/rss/en.xml'
      fullPath: '/rss/en.xml'
      preLoaderRoute: typeof RssEnDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/blog/': {
      id: '/$lang/blog/'
      path: '/blog'
      fullPath: '/$lang/blog/'
      preLoaderRoute: typeof LangBlogIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/blog/$slug': {
      id: '/$lang/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/$lang/blog/$slug'
      preLoaderRoute: typeof LangBlogSlugRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/booking/': {
      id: '/$lang/booking/'
      path: '/booking'
      fullPath: '/$lang/booking/'
      preLoaderRoute: typeof LangBookingIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/booking/$slug': {
      id: '/$lang/booking/$slug'
      path: '/booking/$slug'
      fullPath: '/$lang/booking/$slug'
      preLoaderRoute: typeof LangBookingSlugRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/work/': {
      id: '/$lang/work/'
      path: '/work'
      fullPath: '/$lang/work/'
      preLoaderRoute: typeof LangWorkIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/work/$slug': {
      id: '/$lang/work/$slug'
      path: '/work/$slug'
      fullPath: '/$lang/work/$slug'
      preLoaderRoute: typeof LangWorkSlugRouteImport
      parentRoute: typeof LangRoute
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/$id': {
      id: '/admin/blog/$id'
      path: '/blog/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AdminBlogIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/new': {
      id: '/admin/blog/new'
      path: '/blog/new'
      fullPath: '/admin/blog/new'
      preLoaderRoute: typeof AdminBlogNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/tags': {
      id: '/admin/blog/tags'
      path: '/blog/tags'
      fullPath: '/admin/blog/tags'
      preLoaderRoute: typeof AdminBlogTagsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings/': {
      id: '/admin/bookings/'
      path: '/bookings'
      fullPath: '/admin/bookings/'
      preLoaderRoute: typeof AdminBookingsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings/$id': {
      id: '/admin/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/admin/bookings/$id'
      preLoaderRoute: typeof AdminBookingsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings/availability': {
      id: '/admin/bookings/availability'
      path: '/bookings/availability'
      fullPath: '/admin/bookings/availability'
      preLoaderRoute: typeof AdminBookingsAvailabilityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings/new': {
      id: '/admin/bookings/new'
      path: '/bookings/new'
      fullPath: '/admin/bookings/new'
      preLoaderRoute: typeof AdminBookingsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inbox/': {
      id: '/admin/inbox/'
      path: '/inbox'
      fullPath: '/admin/inbox/'
      preLoaderRoute: typeof AdminInboxIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inbox/$personId': {
      id: '/admin/inbox/$personId'
      path: '/inbox/$personId'
      fullPath: '/admin/inbox/$personId'
      preLoaderRoute: typeof AdminInboxPersonIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inbox/new': {
      id: '/admin/inbox/new'
      path: '/inbox/new'
      fullPath: '/admin/inbox/new'
      preLoaderRoute: typeof AdminInboxNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inbox/settings': {
      id: '/admin/inbox/settings'
      path: '/inbox/settings'
      fullPath: '/admin/inbox/settings'
      preLoaderRoute: typeof AdminInboxSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoices/': {
      id: '/admin/invoices/'
      path: '/invoices'
      fullPath: '/admin/invoices/'
      preLoaderRoute: typeof AdminInvoicesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoices/$invoiceId': {
      id: '/admin/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/admin/invoices/$invoiceId'
      preLoaderRoute: typeof AdminInvoicesInvoiceIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoices/clients': {
      id: '/admin/invoices/clients'
      path: '/invoices/clients'
      fullPath: '/admin/invoices/clients'
      preLoaderRoute: typeof AdminInvoicesClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoices/new': {
      id: '/admin/invoices/new'
      path: '/invoices/new'
      fullPath: '/admin/invoices/new'
      preLoaderRoute: typeof AdminInvoicesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoices/sent': {
      id: '/admin/invoices/sent'
      path: '/invoices/sent'
      fullPath: '/admin/invoices/sent'
      preLoaderRoute: typeof AdminInvoicesSentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoices/subscriptions': {
      id: '/admin/invoices/subscriptions'
      path: '/invoices/subscriptions'
      fullPath: '/admin/invoices/subscriptions'
      preLoaderRoute: typeof AdminInvoicesSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads/': {
      id: '/admin/leads/'
      path: '/leads'
      fullPath: '/admin/leads/'
      preLoaderRoute: typeof AdminLeadsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads/$personId': {
      id: '/admin/leads/$personId'
      path: '/leads/$personId'
      fullPath: '/admin/leads/$personId'
      preLoaderRoute: typeof AdminLeadsPersonIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads/board': {
      id: '/admin/leads/board'
      path: '/leads/board'
      fullPath: '/admin/leads/board'
      preLoaderRoute: typeof AdminLeadsBoardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects/': {
      id: '/admin/projects/'
      path: '/projects'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AdminProjectsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects/$id': {
      id: '/admin/projects/$id'
      path: '/projects/$id'
      fullPath: '/admin/projects/$id'
      preLoaderRoute: typeof AdminProjectsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects/new': {
      id: '/admin/projects/new'
      path: '/projects/new'
      fullPath: '/admin/projects/new'
      preLoaderRoute: typeof AdminProjectsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$lang/booking/manage/$reference': {
      id: '/$lang/booking/manage/$reference'
      path: '/booking/manage/$reference'
      fullPath: '/$lang/booking/manage/$reference'
      preLoaderRoute: typeof LangBookingManageReferenceRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/booking/room/$reference': {
      id: '/$lang/booking/room/$reference'
      path: '/booking/room/$reference'
      fullPath: '/$lang/booking/room/$reference'
      preLoaderRoute: typeof LangBookingRoomReferenceRouteImport
      parentRoute: typeof LangRoute
    }
    '/admin/bookings/$id_/room': {
      id: '/admin/bookings/$id_/room'
      path: '/bookings/$id/room'
      fullPath: '/admin/bookings/$id/room'
      preLoaderRoute: typeof AdminBookingsIdRoomRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings/types/': {
      id: '/admin/bookings/types/'
      path: '/bookings/types'
      fullPath: '/admin/bookings/types/'
      preLoaderRoute: typeof AdminBookingsTypesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings/types/$id': {
      id: '/admin/bookings/types/$id'
      path: '/bookings/types/$id'
      fullPath: '/admin/bookings/types/$id'
      preLoaderRoute: typeof AdminBookingsTypesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings/types/new': {
      id: '/admin/bookings/types/new'
      path: '/bookings/types/new'
      fullPath: '/admin/bookings/types/new'
      preLoaderRoute: typeof AdminBookingsTypesNewRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface LangRouteChildren {
  LangAboutRoute: typeof LangAboutRoute
  LangContactRoute: typeof LangContactRoute
  LangDatenschutzRoute: typeof LangDatenschutzRoute
  LangFaqRoute: typeof LangFaqRoute
  LangImpressumRoute: typeof LangImpressumRoute
  LangServicesRoute: typeof LangServicesRoute
  LangStackRoute: typeof LangStackRoute
  LangIndexRoute: typeof LangIndexRoute
  LangBlogSlugRoute: typeof LangBlogSlugRoute
  LangBookingSlugRoute: typeof LangBookingSlugRoute
  LangWorkSlugRoute: typeof LangWorkSlugRoute
  LangBlogIndexRoute: typeof LangBlogIndexRoute
  LangBookingIndexRoute: typeof LangBookingIndexRoute
  LangWorkIndexRoute: typeof LangWorkIndexRoute
  LangBookingManageReferenceRoute: typeof LangBookingManageReferenceRoute
  LangBookingRoomReferenceRoute: typeof LangBookingRoomReferenceRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangAboutRoute: LangAboutRoute,
  LangContactRoute: LangContactRoute,
  LangDatenschutzRoute: LangDatenschutzRoute,
  LangFaqRoute: LangFaqRoute,
  LangImpressumRoute: LangImpressumRoute,
  LangServicesRoute: LangServicesRoute,
  LangStackRoute: LangStackRoute,
  LangIndexRoute: LangIndexRoute,
  LangBlogSlugRoute: LangBlogSlugRoute,
  LangBookingSlugRoute: LangBookingSlugRoute,
  LangWorkSlugRoute: LangWorkSlugRoute,
  LangBlogIndexRoute: LangBlogIndexRoute,
  LangBookingIndexRoute: LangBookingIndexRoute,
  LangWorkIndexRoute: LangWorkIndexRoute,
  LangBookingManageReferenceRoute: LangBookingManageReferenceRoute,
  LangBookingRoomReferenceRoute: LangBookingRoomReferenceRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

interface AdminRouteChildren {
  AdminContentRoute: typeof AdminContentRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBlogIdRoute: typeof AdminBlogIdRoute
  AdminBlogNewRoute: typeof AdminBlogNewRoute
  AdminBlogTagsRoute: typeof AdminBlogTagsRoute
  AdminBookingsIdRoute: typeof AdminBookingsIdRoute
  AdminBookingsAvailabilityRoute: typeof AdminBookingsAvailabilityRoute
  AdminBookingsNewRoute: typeof AdminBookingsNewRoute
  AdminInboxPersonIdRoute: typeof AdminInboxPersonIdRoute
  AdminInboxNewRoute: typeof AdminInboxNewRoute
  AdminInboxSettingsRoute: typeof AdminInboxSettingsRoute
  AdminInvoicesInvoiceIdRoute: typeof AdminInvoicesInvoiceIdRoute
  AdminInvoicesClientsRoute: typeof AdminInvoicesClientsRoute
  AdminInvoicesNewRoute: typeof AdminInvoicesNewRoute
  AdminInvoicesSentRoute: typeof AdminInvoicesSentRoute
  AdminInvoicesSubscriptionsRoute: typeof AdminInvoicesSubscriptionsRoute
  AdminLeadsPersonIdRoute: typeof AdminLeadsPersonIdRoute
  AdminLeadsBoardRoute: typeof AdminLeadsBoardRoute
  AdminProjectsIdRoute: typeof AdminProjectsIdRoute
  AdminProjectsNewRoute: typeof AdminProjectsNewRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
  AdminBookingsIndexRoute: typeof AdminBookingsIndexRoute
  AdminInboxIndexRoute: typeof AdminInboxIndexRoute
  AdminInvoicesIndexRoute: typeof AdminInvoicesIndexRoute
  AdminLeadsIndexRoute: typeof AdminLeadsIndexRoute
  AdminProjectsIndexRoute: typeof AdminProjectsIndexRoute
  AdminBookingsIdRoomRoute: typeof AdminBookingsIdRoomRoute
  AdminBookingsTypesIdRoute: typeof AdminBookingsTypesIdRoute
  AdminBookingsTypesNewRoute: typeof AdminBookingsTypesNewRoute
  AdminBookingsTypesIndexRoute: typeof AdminBookingsTypesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminContentRoute: AdminContentRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBlogIdRoute: AdminBlogIdRoute,
  AdminBlogNewRoute: AdminBlogNewRoute,
  AdminBlogTagsRoute: AdminBlogTagsRoute,
  AdminBookingsIdRoute: AdminBookingsIdRoute,
  AdminBookingsAvailabilityRoute: AdminBookingsAvailabilityRoute,
  AdminBookingsNewRoute: AdminBookingsNewRoute,
  AdminInboxPersonIdRoute: AdminInboxPersonIdRoute,
  AdminInboxNewRoute: AdminInboxNewRoute,
  AdminInboxSettingsRoute: AdminInboxSettingsRoute,
  AdminInvoicesInvoiceIdRoute: AdminInvoicesInvoiceIdRoute,
  AdminInvoicesClientsRoute: AdminInvoicesClientsRoute,
  AdminInvoicesNewRoute: AdminInvoicesNewRoute,
  AdminInvoicesSentRoute: AdminInvoicesSentRoute,
  AdminInvoicesSubscriptionsRoute: AdminInvoicesSubscriptionsRoute,
  AdminLeadsPersonIdRoute: AdminLeadsPersonIdRoute,
  AdminLeadsBoardRoute: AdminLeadsBoardRoute,
  AdminProjectsIdRoute: AdminProjectsIdRoute,
  AdminProjectsNewRoute: AdminProjectsNewRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
  AdminBookingsIndexRoute: AdminBookingsIndexRoute,
  AdminInboxIndexRoute: AdminInboxIndexRoute,
  AdminInvoicesIndexRoute: AdminInvoicesIndexRoute,
  AdminLeadsIndexRoute: AdminLeadsIndexRoute,
  AdminProjectsIndexRoute: AdminProjectsIndexRoute,
  AdminBookingsIdRoomRoute: AdminBookingsIdRoomRoute,
  AdminBookingsTypesIdRoute: AdminBookingsTypesIdRoute,
  AdminBookingsTypesNewRoute: AdminBookingsTypesNewRoute,
  AdminBookingsTypesIndexRoute: AdminBookingsTypesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminLoginRoute: AdminLoginRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiContactRoute: ApiContactRoute,
  ApiInboundEmailRoute: ApiInboundEmailRoute,
  RssArDotxmlRoute: RssArDotxmlRoute,
  RssDeDotxmlRoute: RssDeDotxmlRoute,
  RssEnDotxmlRoute: RssEnDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from '../../start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
